### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by ezl0l** [BRUHItsABunny/go-android-firebase#1]
Hi! Have you stopped developing a push notification listener?
I would be very grateful to you if you share your best practices (if any).
Thank you!

(English is not my native language, I apologize for possible mistakes)

**Comment by BRUHItsABunny** [comment]
Occasionally I still work on it, I will check back with you later this week to see how much is still left to do.

**Comment by ezl0l** [comment]
@BRUHItsABunny I found solution but it wrote on Python https://github.com/Francesco149/push_receiver 
upd: it's python fork of https://github.com/MatthieuLemoine/push-receiver

**Comment by BRUHItsABunny** [comment]
Thanks for the share, I will look into it and add it to my research
Simply seeing it in a different language can do wonders sometimes

I do want to point out though that the original work of Matthieu Lemoine was a reversed version of the chromium push notifications while mine will by a version on the Android implementation instead (mostly the same, just slightly more complex but a lot more stable)

**Comment by BRUHItsABunny** [comment]
My apologies, I got sick and was unable to proceed with my research.
I am resuming today.

**Comment by k0ngoz** [comment]
Any news @BRUHItsABunny?
I would be very very interested in an implementation as well!

**Comment by BRUHItsABunny** [comment]
I remember where I got stuck btw, in every implementation anyone else has done so far they went after the chromium version of push notifications which has the following API flow:
```
checkin
c2dm register3
fcm register
mtalk socket
```

Whereas android doesn't seem to do that the same way, I has been able to catch the following flow:
```
checkin
c2dm register3
mtalk socket
```
it misses the fcm registration, which in every other implementation ([python](https://github.com/Francesco149/push_receiver/blob/master/push_receiver/push_receiver.py#L163), [javascript](https://github.com/MatthieuLemoine/push-receiver/blob/master/src/fcm/index.js#L10)) is how they establish the encryption keys for notification payloads (it seems?) 

(yes i am aware this is microg and not the actual google play services/gsm implementation - this was the easiest to show at 4am)
![WhatsApp Image 2022-12-29 at 10 46 33](https://user-images.githubusercontent.com/53124399/209934008-5e273e07-1053-4d43-a68d-1efe1df8291d.jpg)


Now [this issue](https://github.com/microg/GmsCore/issues/1677) however sheds some light into the situation
Because microg push notifications work - but maybe not for web apps trying to send notifications to the browser on an android phone

If this is the case, then i might just be overcomplicating things for myself
I will probably have to find a better way to test this though, might just reset my phone again and capture Google's implementation instead

in Brave browser on android I was able to recreate push notifications (only tested two sites) but the fcm registration was replaced with an api call to some endpoint from the websites i was trying to get push notifications from - the data it sent however was identical to a regular fcm registration (as far as data fields go, not necessarily the values)[

[This](https://github.com/MatthieuLemoine/push-receiver/pull/12) seems to account for android app registrationsish, it's old but might be a good starting point

[related issue](https://github.com/microg/GmsCore/issues/1859) over at MicroG

**Comment by BRUHItsABunny** [comment]
I should have a working POC by the end of next week, at least for native apps
 Implementing web push is slightly different and might require more testing

**Comment by BRUHItsABunny** [comment]
I just managed to connect and login via the TCP socket just now and keep it alive (longest test was 1hr), haven't seen a notification yet but I am working on a way to produce notifications on demand next

After that I still need to design a sensible API to expose this to the user, suggestions are welcome for this in the meantime

**Comment by BRUHItsABunny** [comment]
I have a working POC, triggers a push notification upon run and it shows up via the mtalk connection.
Just one thing to consider though and that is that every app has a different way of handling the notifications entirely, so this needs to be done on a per-app basis

[output](https://pastebin.com/83NgENE0)
